fos_user:
    from_email:
        address: "%mailer_email%"
        sender_name: "%mailer_name%"
    service:
        user_manager: ItkDev\EasyAdminUserBundle\Service\UserManager
        mailer: fos_user.mailer.twig_swift
    resetting:
        token_ttl: 86400
        email:
            template: '@EasyAdminUser/Email/password_resetting.email.twig'
